class TradingContext:
    """
    Shared object that stores every intermediate result
    generated by the Trading Decision System.

    Every detector reads from and writes to this object.
    """

    def __init__(self):

        self.reset()

    def reset(self):

        # ==========================
        # Raw Market Data
        # ==========================
        self.ohlc = None

        # ==========================
        # Market Structure
        # ==========================
        self.swings = None
        self.structure = None

        # ==========================
        # Events
        # ==========================
        self.bos = None
        self.choch = None

        # ==========================
        # Trend State
        # ==========================
        self.market_state = None

        # ==========================
        # Zones
        # ==========================
        self.order_blocks = None
        self.supply = None
        self.demand = None
        self.fvg = None

        # ==========================
        # Strategy
        # ==========================
        self.signals = None